services:
  - type: web
    name: free-host
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /opt/render/data/data
      - key: SITES_DIR
        value: /opt/render/data/sites
      - key: JWT_SECRET
        generateValue: true
      - key: GITHUB_TOKEN
        sync: false